data = [
    'Instituto Federal do Acre (IFAC)',
    'Instituto Federal de Alagoas (IFAL)',
    'Instituto Federal do Amazonas (IFAM)',
    'Instituto Federal do Amapá (IFAP)',
    'Instituto Federal de Brasília (IFB)',
    'Instituto Federal da Bahia (IFBA)',
    'Instituto Federal Baiano (IFBAIANO)',
    'Instituto Federal Catarinense (IFC)',
    'Instituto Federal do Ceará (IFCE)',
    'Instituto Federal do Espírito Santo (IFES)',
    'Instituto Federal Fluminense (IFF)',
    'Instituto Federal Farroupilha (IFFarroupilha)',
    'Instituto Federal Goiano (IF GOIANO)',
    'Instituto Federal do Maranhão (IFMA)',
    'Instituto Federal de Mato Grosso do Sul (IFMS)',
    'Instituto Federal de Mato Grosso (IFMT)',
    'Instituto Federal do Norte de Minas Gerais (IFNMG)',
    'Instituto Federal do Pará (IFPA)',
    'Instituto Federal da Paraiba (IFPB)',
    'Instituto Federal de Pernambuco (IFPE)',
    'Instituto Federal do Piauí (IFPI)',
    'Instituto Federal do Paraná (IFPR)',
    'Instituto Federal do Rio de Janeiro (IFRJ)',
    'Instituto Federal do Rio Grande do Norte (IFRN)',
    'Instituto Federal de Rondônia (IFRO)',
    'Instituto Federal de Roraima (IFRR)',
    'Instituto Federal do Rio Grande do Sul (IFRS)',
    'Instituto Federal de Sergipe (IFS)',
    'Instituto Federal de Santa Catarina (IFSC)',
    'Instituto Federal do Sertão Pernambucano (IFSERTÃOPE)',
    'Instituto Federal de São Paulo (IFSP)',
    'Instituto Federal Sul-rio-grandense (IFSul)',
    'Instituto Federal do Sul de Minas Gerais (IFSuldeMinas)',
    'Instituto Federal do Triângulo Mineiro (IFTM)',
    'Instituto Federal do Tocantins (IFTO)',
    'Central de Ensino e Desenvolvimento Agrário de Florestal (CEDAF / UFV)',
    'Centro de Educação Profissional (Cefores / UFTM)',
    'Centro Federal de Educação Tecnológica de Minas Gerais (Cefet / MG)',
    'Colégio Técnico de Bom Jesus (CTBJ / UFPI)',
    'Colégio Universitário - Universidade Federal do Maranhão (COLUN / UFMA)',
    'Colégio Técnico da Universidade Rural (CTUR / UFRRJ)',
    'Colégio Técnico de Teresina  (CTT / UFPI)',
    'Colégio Agrícola Vidal de Negreiros (CAVN / UFPB)',
    'Colégio Técnico de Floriano (CTF / UFPI)',
    'Escola Técnica de Saúde - Universidade Federal de Uberlândia (ESTES / UFU)',
    'Escola Agrícola de Jundiaí - Universidade Federal do Rio Grande do Norte (EAJ / UFRN)',
    'Escola Técnica de Saúde de Cajazeiras (ETSC / UFCG)',
    'Escola Técnica de Saúde - Universidade Federal da Paraíba (ETS / UFPB)',
    'Escola de Música - Universidade Federal do Rio Grande do Norte (UFRN)',
    'Universidade Federal Rural de Pernambuco (UFRPE)',
    'Escola de Saúde - Universidade Federal do Rio Grande do Norte (ESUFRN)',
    'Teatro Universitário - Universidade Federal de Minas Gerais (TU/UFMG)',
    'Escola vinculada à SEE do Amazonas (Seduc) (ETSUS / AM - CETAM)',
    'Fundação Estadual de Saúde de Sergipe (ETSUS / SE - FUNESA)',
    'Escola Técnica de Saúde de Alagoas - Universidade Estadual de Ciências da Saúde de Alagoas (ETSUS / AL - Etsal / Uncisal)',
    'Escola Polit. de Saúde Joaquim Venâncio - Fiocruz (ETSUS / RJ - EPSJV)',
    'Escola de Saúde Pública Visconde de Sabóia (ETSUS / CE)',
    'Secretaria Municipal de Saúde de Vitória (ETSUS / ES)',
    'Escola Técnica de Saúde do SUS de Roraima (ETSUS / RR)',
    'Escola de Governo em Saúde Pública de Pernambuco (ETSUS / PE)',
    'Piraquera Açu - Escola de Auxiliar de Enfermagem HRLB (ETSUS / SP)',
    'Escola de Formação Técnica em Saúde Enfermeira Izabel Santos (ETSUS / RJ)',
    'Centro de Educação Profissional Escola Técnica de Planaltina (ETSUS / DF)',
    'Escola de Saúde Pública do Estado de Mato Grosso  (ETSUS / MT - SES/MT)',
    'Escola Técnica do Sistema Único de Saúde Blumenau (ETSUS / SC)',
    'Escola de Saúde Pública de Santa Catarina (ETSUS / ESPSC)',
    'Escola Estadual de Saúde Pública do Piauí (ETSUS / PI)',
    'Franco da Rocha (ETSUS / SP)',
    'Escola de Saúde Pública do Paraná (ETSUS ESPP CFRH)',
    'CEFORSUS Araraquara (ETSUS / SP)',
    'Escola de Saúde Bahia Prof. Jorge Novis (ETSUS)',
    'Escola de Saúde - Universidade Federal do Maranhão (ETSUS / MA - UFMA)',
    'Escola Técnica do SUS-SP (ETSUS / SP)',
    'Centro de Educação Tecnológica do Amazonas (CETAM / COTEP)',
    'Escola Municipal de Saúde de São Paulo (ETSUS / SP)',
    'Escola Técnica de Saúde de Brasília (ETSUS / DF)',
    'Colégio Agrícola Vidal de Negreiros (CAVN)',
    'Escola de Saúde da Universidade Federal do Rio Grande do Norte (ES / UFRN)',
    'Centro de Educação Profissional  (Cefores / UFTM)',
    'Escola Técnica de Artes da Universidade Federal de Alagoas (ETA / UFAL)',
    'Colégio Técnico de Teresina (UFPI)',
    'Escola Agrotécnica da Universidade Federal de Roraima  (EAgro / UFRR)',
    'Centro Profissional e Tecnológico Escola Técnica de Saúde  (UFPB)',
    'Colégio Agrícola Dom Agostinho Ikas da Universidade Federal Rural de Pernambuco (CODAI / UFRPE)',
    'Colégio Técnico da Universidade Federal de Minas Gerais (COLTEC / UFMG)',
    'Escola Agrícola de Jundiaí  (EAJ / UFRN)',
    'Colégio Técnico da Universidade Federal Rural do Rio de Janeiro (CTUR / UFRRJ)',
    'Serviço Nacional de Aprendizagem Rural (Senar Nacional)',
    'Serviço Nacional de Aprendizagem do Comércio - Departamento Nacional (Senac - DN)',
    'Serviço Nacional de Aprendizagem do Comércio - Acre (Senac - AC)',
    'Serviço Nacional de Aprendizagem do Comércio - Alagoas (Senac - AL)',
    'Serviço Nacional de Aprendizagem do Comércio - Amapá (Senac - AP)',
    'Serviço Nacional de Aprendizagem do Comércio - Amazonas (Senac - AM)',
    'Serviço Nacional de Aprendizagem do Comércio - Bahia (Senac - BA)',
    'Serviço Nacional de Aprendizagem do Comércio - Ceará (Senac - CE)',
    'Serviço Nacional de Aprendizagem do Comércio - Distrito Federal (Senac - DF)',
    'Serviço Nacional de Aprendizagem do Comércio - Espírito Santo (Senac - ES)',
    'Serviço Nacional de Aprendizagem do Comércio - Goiás (Senac - GO)',
    'Serviço Nacional de Aprendizagem do Comércio - Maranhão (Senac - MA)',
    'Serviço Nacional de Aprendizagem do Comércio - Minas Gerais (Senac - MG)',
    'Serviço Nacional de Aprendizagem do Comércio - Mato Grosso do Sul (Senac - MS)',
    'Serviço Nacional de Aprendizagem do Comércio - Mato Grosso (Senac - MT)',
    'Serviço Nacional de Aprendizagem do Comércio - Pará (Senac - PA)',
    'Serviço Nacional de Aprendizagem do Comércio - Paraíba (Senac - PB)',
    'Serviço Nacional de Aprendizagem do Comércio - Pernambuco (Senac - PE)',
    'Serviço Nacional de Aprendizagem do Comércio - Piauí (Senac - PI)',
    'Serviço Nacional de Aprendizagem do Comércio - Paraná (Senac - PR)',
    'Serviço Nacional de Aprendizagem do Comércio - Rio Grande do Norte (Senac - RN)',
    'Serviço Nacional de Aprendizagem do Comércio - Rio de Janeiro (Senac - RJ)',
    'Serviço Nacional de Aprendizagem do Comércio - Rondônia (Senac - RO)',
    'Serviço Nacional de Aprendizagem do Comércio - Roraima (Senac - RR)',
    'Serviço Nacional de Aprendizagem do Comércio - Rio Grande do Sul (Senac - RS)',
    'Serviço Nacional de Aprendizagem do Comércio - Santa Catarina (Senac - SC)',
    'Serviço Nacional de Aprendizagem do Comércio - São Paulo (Senac - SP)',
    'Serviço Nacional de Aprendizagem do Comércio - Sergipe (Senac - SE)',
    'Serviço Nacional de Aprendizagem do Comércio - Tocantins (Senac - TO)',
    'Serviço Nacional de Aprendizagem Industrial - Departamento Nacional (Senai - DN)',
    'Serviço Nacional de Aprendizagem Industrial - Acre (Senai - AC)',
    'Serviço Nacional de Aprendizagem Industrial - Alagoas (Senai - AL)',
    'Serviço Nacional de Aprendizagem Industrial - Amapá (Senai - AP)',
    'Serviço Nacional de Aprendizagem Industrial - Amazonas (Senai - AM)',
    'Serviço Nacional de Aprendizagem Industrial - Bahia (Senai - BA)',
    'Serviço Nacional de Aprendizagem Industrial - Ceará (Senai - CE)',
    'Serviço Nacional de Aprendizagem Industrial - Distrito Federal (Senai - DF)',
    'Serviço Nacional de Aprendizagem Industrial - Espírito Santo (Senai - ES)',
    'Serviço Nacional de Aprendizagem Industrial - Goiás (Senai - GO)',
    'Serviço Nacional de Aprendizagem Industrial - Maranhão (Senai - MA)',
    'Serviço Nacional de Aprendizagem Industrial - Minas Gerais (Senai - MG)',
    'Serviço Nacional de Aprendizagem Industrial - Mato Grosso do Sul (Senai - MS)',
    'Serviço Nacional de Aprendizagem Industrial - Mato Grosso (Senai - MT)',
    'Serviço Nacional de Aprendizagem Industrial - Pará (Senai - PA)',
    'Serviço Nacional de Aprendizagem Industrial - Paraíba (Senai - PB)',
    'Serviço Nacional de Aprendizagem Industrial - Pernambuco (Senai - PE)',
    'Serviço Nacional de Aprendizagem Industrial - Piauí (Senai - PI)',
    'Serviço Nacional de Aprendizagem Industrial - Paraná (Senai - PR)',
    'Serviço Nacional de Aprendizagem Industrial - Rio Grande do Norte (Senai - RN)',
    'Serviço Nacional de Aprendizagem Industrial - Rio de Janeiro (Senai - RJ)',
    'Serviço Nacional de Aprendizagem Industrial - Rondônia (Senai - RO)',
    'Serviço Nacional de Aprendizagem Industrial - Roraima (Senai - RR)',
    'Serviço Nacional de Aprendizagem Industrial - Rio Grande do Sul (Senai - RS)',
    'Serviço Nacional de Aprendizagem Industrial - Santa Catarina (Senai - SC)',
    'Serviço Nacional de Aprendizagem Industrial - São Paulo (Senai - SP)',
    'Serviço Nacional de Aprendizagem Industrial - Sergipe (Senai - SE)',
    'Serviço Nacional de Aprendizagem Industrial - Tocantins (Senai - TO)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Acre (Sest Senat - AC)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Alagoas (Sest Senat - AL)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Amapá (Sest Senat - AP)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Amazonas (Sest Senat - AM)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Bahia (Sest Senat - BA)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Ceará (Sest Senat - CE)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Distrito Federal (Sest Senat - DF)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Espírito Santo (Sest Senat - ES)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Goiás (Sest Senat - GO)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Maranhão (Sest Senat - MA)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Mato Grosso (Sest Senat - MT)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Mato Grosso do Sul (Sest Senat - MS)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Minas Gerais (Sest Senat - MG)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Pará (Sest Senat - PA)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Paraíba (Sest Senat - PB)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Paraná  (Sest Senat - PR)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Pernambuco (Sest Senat - PE)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Piauí (Sest Senat - PI)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Rio de Janeiro (Sest Senat - RJ)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Rio Grande do Norte (Sest Senat - RN)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Rio Grande do Sul  (Sest Senat - RS)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Rondônia  (Sest Senat - RO)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Roraima  (Sest Senat - RR)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Santa Catarina  (Sest Senat - SC)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - São Paulo  (Sest Senat - SP)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Sergipe  (Sest Senat - SE)',
    'Serviço Social do Transporte e Serviço Nacional de Aprendizagem do Transporte - Tocantins  (Sest Senat - TO)',
    'Fundação de Educação Profissional e Administração Pública de Itajaí',
    'Centro Estadual de Educação Tecnológica "Paula Souza"',
    'Centro de Educação Tecnológica do Amazonas  (CETAM)'
]
